// <auto-generated />
namespace RHEVENT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class m444 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m444));
        
        string IMigrationMetadata.Id
        {
            get { return "202012230739556_m444"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
