// <auto-generated />
namespace RHEVENT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class da4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(da4));
        
        string IMigrationMetadata.Id
        {
            get { return "202102080922467_da4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
